# Generated by Django 5.0.2 on 2024-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('lon', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
                ('pressure', models.CharField(max_length=30)),
                ('humidity', models.CharField(max_length=30)),
                ('visibility', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
